baseURL: "https://cambuchi.github.io/blog"
title: Cam Nguyen | Blog
paginate: 5
theme: "PaperMod"
copyright: © [Cam Nguyen](https://cambuchi.github.io/blog).

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Cam Nguyen | Blog
  description: "Cam's personal blog."
  keywords: [Blog, Portfolio, Hugo, PaperMod, Forestry, Javascript]
  # author: Cam Nguyen
  # author: ["Me", "You"] # multiple authors
  images: ["catgod.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark #auto, dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "favicon-32x32.png"

  label:
    text: "Cam Nguyen | Blog"
    # icon: apple-touch-icon.png
    # iconHeight: 25

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi, I'm Cam!"
    Image: >
      ![Cam Nguyen Headshot](me.jpg#me)
    Content: 
      Welcome to my blog. This is a place for me to mostly talk about my
      developments in coding. I am a first generation immigrant from Vietnam 
      who is currently trying to become a software developer.  

      
      - 


      - You can reach me at cam.manh.nguyen@gmail.com. 
      
      - Let's keep in touch!

  socialIcons:
    - name: linkedin
      url: "https://github.com/"
    - name: github
      url: "https://github.com/"


  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: projects
      name: projects
      url: /tags/
      weight: 20
    - identifier: resume
      name: resume
      url: https://example.org
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: false
markup:
    highlight:
        anchorLineNos: false
        codeFences: true
        guessSyntax: true
        lineNos: true
        style: vulcan
        # noClasses: true
        tabWidth: 2