baseURL: 'https://cambuchi.github.io/blog'
title: cam nguyen | blog
paginate: 5
theme: 'PaperMod'
copyright: © [Cam Nguyen](https://cambuchi.github.io/blog).

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: cam nguyen | blog
  description: "Cam's personal blog."
  keywords: [Blog, Portfolio, Coding]
  # author: Cam Nguyen
  # author: ["Me", "You"] # multiple authors
  images: ['catgod.jpg']
  DateFormat: 'January 2, 2006'
  defaultTheme: dark #auto, dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: 'files/favicon.ico'
    favicon16x16: 'files/favicon-16x16.png'
    favicon32x32: 'files/favicon-32x32.png'
    apple_touch_icon: 'files/apple-touch-icon.png'
    safari_pinned_tab: 'files/favicon-32x32.png'

  label:
    text: 'cam nguyen | blog'
    # icon: teapot.png
    # iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: 'This is subtitle'
    imageUrl: '<img location>'
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi, I'm Cam!"
    Image: >
      ![Cam Nguyen Headshot](files/me.jpg#me)
    Content: Welcome to my blog. This is a place for me to mostly talk about my
      developments in coding. Based in California, I am a first generation
      immigrant from Vietnam currently trying to become a software developer.
      Previously at Azel, Ridge, Princeton.
    Connect: You can reach me at cam.manh.nguyen@gmail.com.
    Connect2: Let's keep in touch!

  socialIcons:
    - name: linkedin
      url: 'https://www.linkedin.com/in/cam-nguyen-6a1ab257/'
    - name: github
      url: 'https://github.com/Cambuchi'

  analytics:
    google:
      SiteVerificationTag: 'XYZabc'
    bing:
      SiteVerificationTag: 'XYZabc'
    yandex:
      SiteVerificationTag: 'XYZabc'

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: 'https://github.com/Cambuchi/blog-src/blob/main/content'
    Text: 'Suggest Changes' # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ['title', 'permalink', 'summary', 'content', 'desc', 'entry-header']
menu:
  main:
    - identifier: home
      name: home
      url: https://cambuchi.github.io/
      weight: 1
    - identifier: search
      name: search
      url: /search/
      weight: 2
    - identifier: tags
      name: tags
      url: /tags/
      weight: 3
    - identifier: projects
      name: projects
      url: /projects/
      weight: 4
    - identifier: resume
      name: resume
      url: https://cambuchi.github.io/resume/
      weight: 5
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: false
markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: base16-snazzy
    # noClasses: true
    tabWidth: 2
